### ISSUE TITLE
enhanced_img2img, 在没有勾选"Use another image as ControlNet input"时出错

### ISSUE THREAD

**Issue by lsby** [OedoSoldier/enhanced-img2img#22]
提示`UnboundLocalError: local variable 'cn_images' referenced before assignment`.
因为在[这](https://github.com/OedoSoldier/enhanced-img2img/blob/15eb9d79fc92c022eed3b399da38f97a30a5d6b4/scripts/enhanced_img2img.py#L492), 判断`cn_images不为None`和`use_cn为true`, 这是没有必要的, 因为从上面的代码看, 当use_cn不为true时, cn_images一定是None.
因为很简单我就不提pr了.

完整的堆栈:
```
Will process following files: C:\Users\hbyBy\Desktop\输入\aaa.png
Processing: C:\Users\hbyBy\Desktop\输入\aaa.png
Error completing request
Arguments: ('task(a4p3ppt5wwnlzr4)', 0, '', '', [], <PIL.Image.Image image mode=RGBA size=512x512 at 0x1AD5046F7C0>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', '', [], 10, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, False, 0, True, 384, 384, False, 2, True, True, False, False, 'C:\\Users\\hbyBy\\Desktop\\输入', 'C:\\Users\\hbyBy\\Desktop\\输出', 'C:\\Users\\hbyBy\\Desktop\\蒙版', False, True, False, False, False, 50, '0', False, '', False, False, False, '', False,   1 2 3
0      , False, 512, 512, 0.2, '', 'None', '', '', 1, 'FirstGen', False, False, 'Current', False,   1 2 3
0      , False, '', False, '', False, '') {}
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\AI\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\AI\stable-diffusion-webui\modules\img2img.py", line 169, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 399, in run
    processed = script.run(p, *script_args)
  File "D:\AI\stable-diffusion-webui\extensions\enhanced-img2img\scripts\enhanced_img2img.py", line 492, in run
    # if cn_images is not None and use_cn:
UnboundLocalError: local variable 'cn_images' referenced before assignment
```

**Comment by OedoSoldier** [comment]
感谢 report，已经修复。
