### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Enferlain** [OedoSoldier/enhanced-img2img#34]
Was trying to test the multi-frame rendering script, but I get this error. Does anyone know why this happens?

My settings 

![image](https://github.com/OedoSoldier/sd-webui-image-sequence-toolkit/assets/15861396/1d11a96b-ba49-4452-a85a-8080a1e640cb)

![image](https://github.com/OedoSoldier/sd-webui-image-sequence-toolkit/assets/15861396/460843ea-401d-4925-ab05-30f78d38c2eb)

The whole error code:
```
Traceback (most recent call last):
  File "/content/drive/MyDrive/sd22/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/drive/MyDrive/sd22/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/drive/MyDrive/sd22/stable-diffusion-webui/modules/img2img.py", line 170, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "/content/drive/MyDrive/sd22/stable-diffusion-webui/modules/scripts.py", line 407, in run
    processed = script.run(p, *script_args)
  File "/content/drive/MyDrive/sd22/stable-diffusion-webui/extensions/sd-webui-image-sequence-toolkit/scripts/multi_frame_rendering.py", line 254, in run
    reference_imgs = sort_images(reference_imgs)
  File "/content/drive/MyDrive/sd22/stable-diffusion-webui/extensions/sd-webui-image-sequence-toolkit/scripts/ei_utils.py", line 30, in sort_images
    return sorted(lst, key=lambda x: int(re.search(pattern, x).group()))
  File "/content/drive/MyDrive/sd22/stable-diffusion-webui/extensions/sd-webui-image-sequence-toolkit/scripts/ei_utils.py", line 30, in <lambda>
    return sorted(lst, key=lambda x: int(re.search(pattern, x).group()))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by kian996** [comment]
Hi, it should be the naming of the images in your input folder is not standardized, try to follow XX001, XX002 ...... this way of naming.
I encountered the same problem and it works fine after standardizing the image names.

**Comment by Enferlain** [comment]
That was it btw
